#PENSIUNKU
1.TAMBAHKAN ISIAN EMAIL (OPTIONAL) PADA PENDAFTARAN
2.FORM PENGAJUAN DIRI SENDIRI (OK) ,lib di ganti image picker dan nama, no telepon otomatis sudah terisi
3.MEMBUAT MENU UPGRADE AKUN , UNTUK MENGAKTIFKAN FITUR REFERRAL,E WALLET DAN PENGAJUAN UNTUK ORANG LAIN
FORM UPGRADE AKUN YAITU FOTO KTP DAN FOTO SELFIE